name: bus_hikaku

on:
  schedule:
    - cron: "0 14 * * *"
  push:
  workflow_dispatch:

jobs:
  bus_hikaku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "actions/bus_hikaku"
    steps:
    - uses: actions/checkout@v3
    - name: setup node.js
      uses: actions/setup-node@v3 # https://github.com/actions/setup-node#usage
    - name: install dependencies
      run : npm install
    - name: npm run start
      run: sh start.sh
    - name: git commit and git push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -B bus_hikaku
        git add .
        git commit -m "$(date "+%Y-%m-%d")"
        git push origin bus_hikaku
