name: search-rubygems

on:
  schedule:
    - cron: "0 14 * * *"
  push:
  workflow_dispatch:

env:
  LINE_NOTIFY_API_URL: ${{ secrets.LINE_NOTIFY_API_URL }}
  LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}

jobs:
  search-rubygems:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: actions/search_rubygems/Gemfile
      # LINE_NOTIFY_API_URL: ${{ secrets.LINE_NOTIFY_API_URL }}
      # LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: bundle install
      run: |
        bundle install
    - name: run search-rubygems
      run: |
        bundle exec ruby actions/search_rubygems/execute.rb
      # run: |
      #   pwd
      #   bundle exec ruby execute.rb
      # working-directory: ./actions/search_rubygems
      # env:
      #   LINE_NOTIFY_API_URL: ${{ secrets.LINE_NOTIFY_API_URL }}
      #   LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
